- name: 'Get aws-cli'
  command: curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
  
- name: 'Unzip aws-cli'
  command: unzip awscliv2.zip

- name: 'Install aws-cli'
  command: ./aws/install

- name: 'Add Docker GPG apt key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: 'Add Docker Repository'
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: 'Update apt and install docker-ce'
  apt:
    name: docker-ce
    state: latest

- name: 'Ensure docker group exists'
  ansible.builtin.group:
    name: docker
    state: present

- name: 'Add patrick to docker group'
  user:
    name: patrick
    groups: docker
    append: yes

- name: 'Start Docker service'
  service:
    name: docker
    state: started
    enabled: yes

- name: 'Get kubectl binary'
  command: curl -LO https://dl.k8s.io/release/v1.28.11/bin/linux/amd64/kubectl

- name: 'Install kubectl'
  command: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
